import turtle
import tkinter

def Gap():
    t.left(90)
    t.up()
    t.forward(75)
    t.left(90)
    t.down()

def CreateLetterP():
    t.down()
    t.forward(200)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.backward(100)
    t.forward(100)
    t.up()
    t.right(90)
    t.forward(100)

def CreateLetterA():
    t.down()
    t.forward(200)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.backward(100)
    t.forward(100)
    t.right(90)
    t.forward(100)

def CreateLetterY():
    t.up()
    t.forward(100)
    t.down()
    t.forward(100)
    t.backward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(100)
    t.backward(100)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(100)
    t.up()
    t.right(180)
    t.forward(200)


def CreateLetterH():
    t.down()
    t.forward(200)
    t.backward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.backward(200)
    t.right(180)

def CreateDash():
    t.up()
    t.forward(100)
    t.right(90)
    t.down()
    t.forward(100)
    t.right(90)
    t.up()
    t.forward(100)

def ExclamationMark():
    t.circle(3)
    t.up()
    t.left(90)
    t.forward(5)
    t.right(90)
    t.forward(50)
    t.down()
    t.forward(150)

def CreateLetterD():
    t.down()
    t.forward(200)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(200)
    t.right(90)
    t.forward(100)
    t.backward(100)
    t.left(90)

def CreateLetterB():
    t.down()
    t.right(90)
    t.forward(100)
    t.backward(100)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.backward(100)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(200)

t = turtle.Pen()
t.pensize(10)
t.speed(10)
t.up()
t.goto(-450, 200)
t.left(90)
t.heading()
t.pencolor("Red")
CreateLetterH()
Gap()
t.pencolor("Blue")
CreateLetterA()
Gap()
t.pencolor("Pink")
CreateLetterP()
Gap()
t.pencolor("Purple")
CreateLetterP()
Gap()
t.pencolor("Light Blue")
CreateLetterY()
Gap()
t.up()
t.goto(-450, -100)
t.pencolor("Orange")
CreateLetterB()
Gap()
t.pencolor("Black")
CreateDash()
Gap()
t.pencolor("Green")
CreateLetterD()
Gap()
t.pencolor("Red")
CreateLetterA()
Gap()
t.pencolor("Purple")
CreateLetterY()
Gap()
t.up()
t.goto(-375, -400)
t.pencolor("Blue")
CreateLetterA()
Gap()
t.pencolor("Green")
CreateLetterP()
Gap()
t.pencolor("Orange")
CreateLetterP()
Gap()
t.pencolor("Pink")
CreateLetterA()
Gap()
t.pencolor("Light Blue")
ExclamationMark()
tkinter.mainloop()